# Generated by Django 5.0.1 on 2024-01-07 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id_l', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('image_url_small', models.URLField()),
                ('image_url_medium', models.URLField()),
                ('image_url_large', models.URLField()),
                ('categorie_nom', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='livres_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_e', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.livre')),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurProfile',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('historique_categories', models.JSONField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
